---
version: "3"
services:
  dashboard-sync:
    image: docker.io/dttr278/dev:hne-dashboard-sync-latest
    restart: always
    environment:
      - HERO_TRANSFER_PROCESS=${HERO_TRANSFER_PROCESS}
      - HERO_CHECK_PROCESS=${HERO_CHECK_PROCESS}
      - HOT_WALLET_PROCESS=${HOT_WALLET_PROCESS}
      - MATCH_TX_PROCESS=${MATCH_TX_PROCESS}
      - BOX_TRANSFER_PROCESS=${BOX_TRANSFER_PROCESS}
      - LOG_DIR=./logs
      - STARTBLOCK=${STARTBLOCK}
      - RPC=${RPC}
      - MAX_QUERY=${MAX_QUERY}
      - CONNECT_STRING=${CONNECT_STRING}
      - INGAME_HERO_API=${INGAME_HERO_API}
      - MARKETPLACE_API=${MARKETPLACE_API}
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOW_IDS=${ALLOW_IDS}
      - SEND_TELEGRAM=${SEND_TELEGRAM}
      - MARKETPLACE_ADDRESS=${MARKETPLACE_ADDRESS}
      - PACK_NFT_CONTRACT_ADDRESS=${PACK_NFT_CONTRACT_ADDRESS}
      - HERO_NFT_ADDRESS=${HERO_NFT_ADDRESS}
      - HE_TOKEN_ADDRESS=${HE_TOKEN_ADDRESS}
      - HOT_WALLET_ADDRESS=${HOT_WALLET_ADDRESS}
      - SPEND_FEE=${SPEND_FEE}
      - INGAME_QUERY_API=${INGAME_QUERY_API}
      - INGAME_QUERY_API_SECRET=${INGAME_QUERY_API_SECRET}
      - GEAR_NFT_ASCEND_ADDRESS=${GEAR_NFT_ASCEND_ADDRESS}
      - GEAR_NFT_ADDRESS=${GEAR_NFT_ADDRESS}
      - GEAR_START_BLOCK=${GEAR_START_BLOCK}
      - GEAR_NFT_MINT_ADDRESS=${GEAR_NFT_MINT_ADDRESS}
      - MP_X_API_KEY=${MP_X_API_KEY}
    # ports:
    #   - 5000:5000
