name: hne-dashboard-sync build
on:
  push:
    branches: [main]

jobs:    
  docker_build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      RELEASE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/dev:hne-dashboard-sync-latest
      KUBE_NAMESPACE: he
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1

        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_ACCESS_TOKEN}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{env.RELEASE_IMAGE}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_to_dev:
    name: Deploy to development env
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    env:
      TELEGRAM_TO: ${{secrets.TELEGRAM_TO}}
      TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/mp/dashboard-sync
            docker-compose pull
            docker-compose up -d
      - name: send telegram message on deploy to develop environment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ env.TELEGRAM_TOKEN }}
          message: |
            [DEV]
            ${{ github.actor }} push on ${{github.ref_name}} - deploy successfully
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
